### ISSUE TITLE
Adaptation Bus 

### ISSUE THREAD

**Issue by lennvilardi** [pgrimaud/lametric-ratp#1]
Bonjour,
Est-il envisageable d'adapter votre code au bus de l'agglomération de Limoges ?
http://www.stcl.fr/
Merci d'avance

**Comment by pgrimaud** [comment]
Bonjour,

Oui c'est possible, mais ça sera sur une application différente.

**Comment by lennvilardi** [comment]
Je suis preneur :)
Merci d'avance
