### ISSUE TITLE
Please check app configuration for all lines

### ISSUE THREAD

**Issue by dustincoates** [pgrimaud/lametric-ratp#3]
All lines, destinations, and start stations (except the sample given in the README) display the "plase check app configuration" message

For example:
Line: metro4
ID Destination: 90
ID Station: 154

**Comment by pgrimaud** [comment]
Hi, thanks for the information.

This app is plugged to an old RATP API which no longer works since 2 days, due to the release of the new RATP website.
I will plug another middleware to retrieve RATP data as soon as possible.

**Comment by dustincoates** [comment]
hah, poor timing as that's exactly when I got my LaMetric. Thank you!

**Comment by pgrimaud** [comment]
Haha, you're so unlucky. This app worked fine since February 2016 until... yesterday! 💀

**Comment by pgrimaud** [comment]
@dustincoates I just fixed it.

Please reinstall the application on your LaMetric. I also updated the readme for configuration.
Tell me if it works for you.

**Comment by dustincoates** [comment]
@pgrimaud Thanks! Works great. One thing that wasn't so clear to me in the README was what to do with stations that had more than one word or diacritics (for example Hôtel de Ville) but I figured it out.
